# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Leitfaden wissenschaftliches Arbeiten in der Religionswissenschaft
#email: frederik.elwert@rub.de
description: > # this means to ignore newlines until "baseurl:"
  Eine Einführung in Techniken des wissenschaftlichen Arbeitens in der
  Religionswissenschaft. Entstanden am Centrum für religionswissenschaftliche
  Studien (CERES) der Ruhr-Universität Bochum.
baseurl: "/academic-skills" # the subpath of your site, e.g. /blog
url: "http://ceres-rub.github.io" # the base hostname & protocol for your site
twitter_username: CERES_RUB
github_username: CERES-RUB

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
